import { useState } from 'react';
import WorkspaceStateWrapper from '../common/WorkspaceStateWrapper';
import { CheckSquare, ShieldCheck, Clock, UserCheck, X } from 'lucide-react';

interface ApprovalTask {
  id: string;
  title: string;
  requestedBy: string;
  department: string;
  priority: 'Critical' | 'Medium' | 'Low';
  date: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  summary: string;
}

export default function ApprovalHubView() {
  const [loading, setLoading] = useState(false);
  const [tasks, setTasks] = useState<ApprovalTask[]>([
    { id: '1', title: 'Asset Purchase: SKU-482 Heavy Machinery', requestedBy: 'Amit Sharma', department: 'Operations', priority: 'Critical', date: '2026-06-10', status: 'Pending', summary: 'Requisitioning secondary automated manufacturing drill head. Budget approval required (₹4,80,000).' },
    { id: '2', title: 'Workforce Expansion: 3 Senior SREs', requestedBy: 'Elena Rostova', department: 'Engineering', priority: 'Medium', date: '2026-06-11', status: 'Pending', summary: 'Approval for SRE roles budget allocation to resolve ongoing platform downtime events.' },
    { id: '3', title: 'Expense Claim Reimbursement', requestedBy: 'Vikram Mehta', department: 'Sales', priority: 'Low', date: '2026-06-08', status: 'Pending', summary: 'Client travel and hosting expenses for European operations alignment (₹85,000).' },
    { id: '4', title: 'Vendor Switch: Procurement SCM', requestedBy: 'Sanjay Dutt', department: 'Logistics', priority: 'Critical', date: '2026-06-09', status: 'Approved', summary: 'Contract change approval to shift raw component delivery channels due to delays.' }
  ]);

  const handleAction = (id: string, action: 'Approved' | 'Rejected') => {
    setLoading(true);
    setTimeout(() => {
      setTasks(prev => prev.map(t => t.id === id ? { ...t, status: action } : t));
      setLoading(false);
    }, 450);
  };

  const pendingCount = tasks.filter(t => t.status === 'Pending').length;

  return (
    <div className="p-6 space-y-6">
      
      {/* ── HERO BANNER ── */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white/3 border border-white/5 p-6 rounded-2xl">
        <div className="space-y-1.5 text-left">
          <div className="text-[10px] font-bold text-white/45 tracking-widest uppercase flex items-center gap-1.5">
            <CheckSquare size={12} />
            <span>People Operations Suite</span>
          </div>
          <h2 className="text-xl font-bold tracking-tight text-white">Decision & Approval Hub</h2>
          <p className="text-xs text-white/40 max-w-lg leading-relaxed">
            Multi-stage workflow decision center. Validate corporate expenditures, role hires, and compliance requests.
          </p>
        </div>
        <div className="h-10 bg-white/5 border border-white/10 rounded-xl px-4 flex items-center gap-2">
          <Clock size={14} className="text-amber-400" />
          <span className="text-xs font-mono font-bold text-white">{pendingCount} Action Items Pending</span>
        </div>
      </div>

      <WorkspaceStateWrapper loading={loading} skeletonType="list">
        
        {/* ── PIPELINE STATE ROW ── */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-neutral-950/40 border border-white/5 p-4 rounded-2xl flex items-center justify-between">
            <div className="text-left">
              <span className="text-[10px] text-white/40 uppercase font-bold">Autogenerated Requisitions</span>
              <div className="text-xl font-bold text-white mt-1">14</div>
            </div>
            <div className="h-10 w-10 bg-white/5 rounded-xl flex items-center justify-center text-white/40">
              <ShieldCheck size={18} />
            </div>
          </div>
          
          <div className="bg-neutral-950/40 border border-white/5 p-4 rounded-2xl flex items-center justify-between">
            <div className="text-left">
              <span className="text-[10px] text-white/40 uppercase font-bold">Escalated Disputes</span>
              <div className="text-xl font-bold text-amber-500 mt-1">2</div>
            </div>
            <div className="h-10 w-10 bg-amber-500/10 rounded-xl flex items-center justify-center text-amber-500">
              <Clock size={18} />
            </div>
          </div>

          <div className="bg-neutral-950/40 border border-white/5 p-4 rounded-2xl flex items-center justify-between">
            <div className="text-left">
              <span className="text-[10px] text-white/40 uppercase font-bold">SLA Compliance Index</span>
              <div className="text-xl font-bold text-emerald-400 mt-1">99.4%</div>
            </div>
            <div className="h-10 w-10 bg-emerald-500/10 rounded-xl flex items-center justify-center text-emerald-400">
              <UserCheck size={18} />
            </div>
          </div>
        </div>

        {/* ── WORKFLOW DECISION MATRIX ── */}
        <div className="space-y-4 text-left">
          <span className="text-xs font-bold text-white/60 uppercase tracking-wider block">Decision queue</span>
          
          <div className="grid grid-cols-1 gap-4">
            {tasks.filter(t => t.status === 'Pending').map(task => (
              <div 
                key={task.id} 
                className="bg-neutral-950/30 border border-white/5 p-5 rounded-2xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 hover:border-white/10 transition-all"
              >
                <div className="space-y-2 max-w-2xl">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-white">{task.title}</span>
                    <span className={`px-2 py-0.5 rounded text-[8px] font-bold ${
                      task.priority === 'Critical' 
                        ? 'bg-rose-500/10 text-rose-400 border border-rose-500/20' 
                        : 'bg-white/5 text-white/40'
                    }`}>
                      {task.priority} Priority
                    </span>
                  </div>
                  <p className="text-[10px] text-white/40 leading-relaxed">{task.summary}</p>
                  <div className="flex gap-4 text-[9px] text-white/35 font-mono">
                    <span>Requested By: <strong className="text-white/60">{task.requestedBy}</strong> ({task.department})</span>
                    <span>Date Filed: {task.date}</span>
                  </div>
                </div>

                <div className="flex gap-2 w-full md:w-auto shrink-0 justify-end">
                  <button
                    onClick={() => handleAction(task.id, 'Rejected')}
                    className="h-8 w-8 rounded-xl border border-white/5 hover:border-rose-500/20 bg-rose-500/5 hover:bg-rose-500/10 text-rose-400 flex items-center justify-center cursor-pointer transition-all"
                    title="Reject Request"
                  >
                    <X size={14} />
                  </button>
                  <button
                    onClick={() => handleAction(task.id, 'Approved')}
                    className="h-8 px-4 rounded-xl bg-white text-black hover:bg-neutral-200 text-[10px] font-bold flex items-center justify-center gap-1.5 cursor-pointer transition-all"
                  >
                    <UserCheck size={13} />
                    <span>Authorize</span>
                  </button>
                </div>
              </div>
            ))}

            {pendingCount === 0 && (
              <div className="p-8 text-center text-white/30 italic text-xs border border-dashed border-white/10 rounded-2xl">
                No active decisions require your review. Authorization ledger is up to date!
              </div>
            )}
          </div>
        </div>

      </WorkspaceStateWrapper>

    </div>
  );
}
